### ISSUE TITLE
second controller wont function on some games (NHL 94/95, Madden Specifically)

### ISSUE THREAD

**Issue by nickraio** [OpenEmu/GenesisPlus-Core#6] opened 2021-03-25 17:22 UTC
Summary of issue: tried connecting two Wiimotes both through Bluetooth preferences in MacOS as well as through OpenEMU directly in controller settings in separate trials. Renamed one of the controllers to Nintendo RVL-CNT-02 to avoid duplicate names in Bluetooth settings. OpenEMU only recognizes both as Nintendo RVL-CNT-01. Then bought and tried some 8bitDO bluetooth controllers. Same issue. 

Both controllers are recognized when programming controller buttons. Both controllers work with games such as Golden Axe or Double Dragon (2 players function) and Tecmo Super Bowl, but in NHL 94, NHL 95 and Madden 95, can't get second player to work with controllers.

I have tried deleting and reinstalling ROMs. I have tried uninstalling controllers and reinstalling through Bluetooth preferences and through OpenEMU. Have tried going into library/application support/OpenEMU/Bindings and deleting Default.oebindings and then reopening OpenEMU.

Both players will work  in other cores such as MAME, NES or SNES (including NHL 94/95 on Super Nintendo Emulator core). Cannot get 2 players to work on these games in Sega Genesis Core. Seems specific to Genesis Plus core, but only on those games. As stated, tried Double Dragon and Golden Axe in Genesis Core and two player functions perfectly. 

Curiously it will recognize buttons and dpad when trying to enter in controller setting for both controllers but then won't operate player 2. I can use either remote to make player 1 function. 

OpenEmu Version: v2.3.3 experimental
macOS Version: Catalina 10.15.7
Genesis Plus Core 1.7.4.13

**Comment by clobber** [comment] 2021-03-25 17:39
The issue is not specific to your input device, it just appears that there are certain games you are expecting multiplayer support that are not working for you. I need a list of all the games and their MD5 checksums. The EA sports titles you noted are set up to automatically use the "[4 Way Play](https://segaretro.org/4_Way_Play)" addon, meaning support for up to four players and it ought to work.

**Comment by nickraio** [comment] 2021-03-25 21:54
Should I use HxD hex editor to get the checksums?

**Comment by nickraio** [comment] 2021-03-25 22:48
Used HashTab.... MD5 Checksums:

NHL 94: ceecad28ebe174d1edf0673990f877d7
NHL 95: 806140bb90c807ab5b5cfe5697a35114
Madden NFL 95: 994a78144e5cf7fc52150f500f0cda50

**Comment by clobber** [comment] 2022-12-28 08:22
Fixed in https://github.com/OpenEmu/GenesisPlus-Core/commit/d661a9fb57f4cd1b250719d603720e3031c82012. I will notify this ticket when a core update has been released.

**Closed by clobber** 2022-12-28 08:22 UTC
